variables:
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - deploy

staging:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=${HEROKU_APP_NAME}-staging --api-key=${HEROKU_API_KEY}
  only:
    - staging

production:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=${HEROKU_APP_NAME}-prod --api-key=${HEROKU_API_KEY}
  only:
    - main

